### ISSUE TITLE
ドロップダウンアニメーション効果の調整

### ISSUE THREAD

**Issue by Bohemian1506** [Bohemian1506/Graduation-work#130]
# issue名
ドロップダウンアニメーション効果の調整

## 概要
ハンバーガーメニューの開閉時のアニメーション効果を滑らかに調整します。

## 目的
- ユーザーエクスペリエンスの向上
- 視覚的なフィードバックの提供
- Bootstrap標準との整合性維持

## 受け入れ基準
- メニュー開閉時のアニメーションが滑らか
- フェードイン・フェードアウト効果が適切
- アニメーション速度が適切（300ms程度）
- 既存のBootstrap動作を阻害しない
-  CSS transitionが正常に動作

### 変更対象ファイル
- app/assets/stylesheets/components/_header.scss
### 実装内容
- CSS transitionプロパティの追加
- opacity、transformを使用したアニメーション
- Bootstrap collapseクラスとの整合性確保

### CSS実装案
```scss
.dropdown-menu-container {
  transition: all 0.3s ease-in-out;
  
  &.show {
    opacity: 1;
    transform: translateY(0);
  }
  
  &:not(.show) {
    opacity: 0;
    transform: translateY(-10px);
    pointer-events: none;
  }
}

.navbar-collapse {
  transition: height 0.35s ease;
}

// ハンバーガーアイコンのアニメーション
.navbar-toggler-icon {
  transition: transform 0.3s ease;
}

.navbar-toggler[aria-expanded="true"] .navbar-toggler-icon {
  transform: rotate(90deg);
}
```
### 調整ポイント
- transitionのタイミング関数（ease-in-out）
-アニメーション時間の統一（0.3s）
- transformとopacityの組み合わせ使用 

## 関連デザイン
- app/assets/stylesheets/components/_header.scss
